[package]
<<<<<<< HEAD
name = "Triangle"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.17"
winit = "0.28"
cgmath = "0.18"
env_logger = "0.9"
futures = "0.3"
image = "0.24"
log = "0.4"
pollster = "0.3"
bytemuck = { version = "1.13", features = ["derive"] }
anyhow = "1.0"
rand = "0.8"
=======
name = "dot_parser_delta_computator"
version = "0.1.0"
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dot-parser = "0.1"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "dot-delta"
path = "src/main.rs"

>>>>>>> fab47b4 (Add dot_parser_delta_computator project)
