[package]
name = "dot_parser_delta_computator"
version = "0.1.0"
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dot-parser = "0.1"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "dot-delta"
path = "src/main.rs"
